import { Nunito } from "next/font/google"
import "./globals.css"

export const metadata = {
  title: "FSW Barber",
  description: "Generated by create next app",
}
const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`dark ${nunito.variable}`}>
      <body>{children}</body>
    </html>
  )
}
