import { Inter } from "next/font/google"
import { Toaster } from "sonner"
import Footer from "./_components/footer"
import "./globals.css"
import AuthProvider from "./_providers/auth"

const inter = Inter({
  subsets: ["latin"],
})

export const metadata = {
  title: "FSW Barber",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <AuthProvider>
          {children}

          <Toaster />

          <Footer />
        </AuthProvider>
      </body>
    </html>
  )
}
